### ISSUE TITLE
Role Buf missing multi methods

### ISSUE THREAD

**Issue by coke** [perl6/doc#531] opened 2016-05-20 20:27 UTC
> The "Role Buf" page at https://docs.perl6.org/type/Buf is missing
> descriptions for the following multi methods: push, pop, append,
> prepend, shift and unshift, splice

Originally opened as RT #128174 by clifton.wood at gmail.com

**Comment by AlexDaniel** [comment] 2016-05-20 20:55
Duplicate of https://github.com/perl6/doc/issues/530

**Closed by AlexDaniel** 2016-05-20 20:55 UTC
