### ISSUE TITLE
Visual glitch in type graph on Microsoft Edge

### ISSUE THREAD

**Issue by bluebear94** [perl6/doc#252] opened 2015-12-20 02:42 UTC
![tg-oc](https://cloud.githubusercontent.com/assets/2975203/11916171/45be7e56-a699-11e5-85f9-a6b68e4dd3c6.PNG)

When you hover over a type name on a type graph on Microsoft Edge, it moves to the right, placing it off-center.

**Comment by zoffixznet** [comment] 2015-12-20 04:37
Can't reproduce in Win10 Edge version 20.10240.16384.0.

**Comment by AlexDaniel** [comment] 2016-06-17 11:28
Some people managed to reproduce it:
```
Edge 25.10586.0.0
EdgeHTML 13.10586
```
![screenshot](https://files.progarm.org/doc-perl6-edge-bug.png)

**Comment by zoffixznet** [comment] 2017-02-02 16:48
Tracked this down to `text-anchor` bug in Edge: https://connect.microsoft.com/IE/feedback/details/1929738/edge-svg-text-anchor-middle-breaks-when-using-special-characters

Issue still present today with Edge 14

**Comment by molecules** [comment] 2017-08-30 22:47
New URL for bug:  https://developer.microsoft.com/microsoft-edge/platform/issues/5126262/

**Comment by JJ** [comment] 2018-01-26 07:46
I'm closing this one, since it's an external bug. Please feel free to reopen if you think it concerns Perl6 doc.

**Comment by AlexDaniel** [comment] 2018-01-26 08:11
Reopening, but marking with `external` label.

**Comment by JJ** [comment] 2018-01-26 08:34
Somebody should be in charge of tracking it, right? We can't depend on the kindness of others to tell us when this is finally closed.

**Comment by JJ** [comment] 2018-05-07 15:42
Somebody has commented [it's a serious issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5126262/). Maybe somebody will finally pay attention to it...

**Comment by coke** [comment] 2018-05-08 12:14
The comment was six days ago, but after that we get:

```
Bogdan B. 14 hours ago
Changed Status from “Confirmed” to “Won’t fix”
```

Given that, I would say we just close out this ticket.

**Comment by AlexDaniel** [comment] 2018-05-08 12:43
Is it the right bug report? What kind of special characters do we have that cause this?

**Comment by JJ** [comment] 2018-05-08 13:25
That was the one linked originally... And it mentions all the right stuff
there.

**Comment by JJ** [comment] 2018-05-08 18:54
@AlexDaniel probably some character in some other part of the page. I'm closing this, since it's not going to be fixed.

**Closed by JJ** 2018-05-08 18:54 UTC
Labels: external, site
