### ISSUE TITLE
The single argument rule isn't explicitly listed anywhere in the docs or searchable

### ISSUE THREAD

**Issue by MasterDuke17** [perl6/doc#924] opened 2016-09-29 01:24 UTC
If you do a Google search you can find it mentioned some places, but it should probably be called out in traps to avoid.

**Comment by timo** [comment] 2016-10-29 23:50
This is a duplicate of #600, which also has a bit more discussion and explanation. so i'm closing this as duplicate.

**Closed by timo** 2016-10-29 23:50 UTC
Labels: docs
