### ISSUE TITLE
Error when building the documentation with: make html

### ISSUE THREAD

**Issue by chsanch** [perl6/doc#2424] opened 2018-10-28 08:47 UTC
Hi,
I've tried to build the documentation with:

`make html`

But I'm getting this error:

```
Cannot resolve caller handle(Pod::Defn
  Pod::Blo..., :part-config({anchored => True, h...), :pod-name(/language/pod.pod6), :part-number(48), :toc-counter(Pod::To::BigPage::TO...)); none of these signatures match:
    (Pod::Block::Code $node, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Comment $node, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Declarator $node, :$pod-name, :$part-number, :$toc-counter)
    (Pod::Block::Named $node, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Named $node where { ... }, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Named $node where { ... }, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Named $node where { ... }, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Named $node where { ... }, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Para $node, $context where { ... }, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Para $node, $context = Context::None, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Block::Para $node, $context where { ... }, :$pod-name, :$part-number, :$toc-counter)
    (Pod::Block::Table $node, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Config $node, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::FormattingCode $node, $context where { ... }, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context where { ... } = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context = Context::None, :$pod-name, :$part-number, :$toc-counter)
    (Pod::FormattingCode $node where { ... }, $context where { ... }, :$pod-name, :$part-number, :$toc-counter)
    (Pod::Heading $node, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Item $node, :$pod-name, :$part-number, :$toc-counter, :%part-config)
    (Pod::Item $node where { ... }, :$part-number, :$toc-counter, :%part-config)
    (Pod::Raw $node, :$pod-name, :$part-number, :$toc-counter)
    (Str $node, Context $context?, :$pod-name, :$part-number, :$toc-counter)
    (Str $node, Context $context where { ... }, :$pod-name, :$part-number, :$toc-counter)
    (Nil, :$pod-name, :$part-number, :$toc-counter)
  in sub handle at /Users/chsanch/rakudo/install/share/perl6/site/sources/AECBB210A3A07DC20E6B2491D30B4B37D07542DF (Pod::To::BigPage) line 318
  in sub parse-pod-file at /Users/chsanch/rakudo/install/share/perl6/site/resources/9A47DEF5F33A2E9D9B3BEECBE1A2DA8B45DD2E59 line 86
  in block  at /Users/chsanch/rakudo/install/share/perl6/site/resources/9A47DEF5F33A2E9D9B3BEECBE1A2DA8B45DD2E59 line 48
  in sub MAIN at /Users/chsanch/rakudo/install/share/perl6/site/resources/9A47DEF5F33A2E9D9B3BEECBE1A2DA8B45DD2E59 line 47
  in block <unit> at /Users/chsanch/rakudo/install/share/perl6/site/resources/9A47DEF5F33A2E9D9B3BEECBE1A2DA8B45DD2E59 line 100
  in sub MAIN at /Users/chsanch/rakudo/install/share/perl6/site/bin/pod2onepage line 2
  in block <unit> at /Users/chsanch/rakudo/install/share/perl6/site/bin/pod2onepage line 2

make: *** [bigpage] Error 1
```

I've installed all the modules needed with:

`zef --deps-only install .`

And this is my Perl 6 version on MacOS Mojave:
```
This is Rakudo version 2018.09-530-gf81146ae9 built on MoarVM version 2018.09-141-gb2e870c6f
implementing Perl 6.d.
```

**Comment by JJ** [comment] 2018-10-28 09:44
I would say it's a Pod::To::Bigpage error, but I'll check and try to reproduce it.

**Comment by JJ** [comment] 2018-10-28 09:46
I could reproduce it, and it's a problem with Pod::Defn in that page. I'll try to fix it there.

**Comment by tbrowder** [comment] 2018-10-28 11:07
See if Rakudo PR #2439 fixes this.

**Comment by hankache** [comment] 2018-11-27 08:32
Still not working.

**Comment by coke** [comment] 2018-11-27 21:31
How is this not breaking the build?

**Comment by coke** [comment] 2018-11-27 21:34
Link to Rakudo PR (above link is to the DOC PR) https://github.com/rakudo/rakudo/pull/2439

**Comment by coke** [comment] 2018-11-27 21:37
That PR has been merged to rakudo master, error is still occurring.

**Comment by coke** [comment] 2018-11-27 21:47
This is not breaking the build because the site is being built with an old version of rakudo:

```
+ echo 'Building docs for 98ed216de31d81926dd48cf8121dc6862db27e24 with ' This is Rakudo version 2018.03-148-g916b41a21 built on MoarVM version 2018.03-68-ged4201e92 implementing Perl 6.c.
```
from https://docs.perl6.org/build-log/

**Comment by JJ** [comment] 2018-11-28 07:03
Which is probably the reason why it's not been upgraded yet...

**Comment by coke** [comment] 2018-12-07 14:46
Someone updated rakudo on docs.perl6.org so now this bug is impacting the live site.

**Comment by JJ** [comment] 2018-12-07 17:08
We actually need Defn on the documentation now, after it's been incorporated by @finanalyst. I guess that meanwhile it's fixed we'll have to go back to 2018.06 or latest before this...

**Comment by JJ** [comment] 2018-12-07 17:09
Besides, those logs are really old...

**Comment by JJ** [comment] 2018-12-07 17:11
I'll check the latest version for this bug also... It should have been fixed.

**Comment by JJ** [comment] 2018-12-07 17:15
That was patched by @finanalyst just today: perl6/perl6-pod-to-bigpage#33

**Comment by coke** [comment] 2018-12-07 20:38
The logs are not old: they're sorted in reverse order, however (look to the bottom) Updating the app config doesn't mean that the installed versions on the doc site are updated; we need to do a zef install-deps on the site. Checking that now.

**Comment by coke** [comment] 2018-12-07 21:01
Doesn't look like 0.5.0 is an available version for me yet. I just did a force install of the module, and only got 0.4.0 (and it keeps telling me it's up to date otherwise, and zef doesn't complain when you do an install-deps about not having that version, so I'm not sure the META6.json is being enforced.

**Comment by JJ** [comment] 2018-12-08 08:07
I just upgraded it. Can you please check?

**Comment by JJ** [comment] 2018-12-08 09:01
It's working now, and it works. The main problem is that, with old versions of perl6, it will not render Defn. I'll try and see where I insert a warning for that and will close this again.

**Closed** 2018-12-08 09:07 UTC
Labels: bug, build, site
