### ISSUE TITLE
Make abbreviations of Language/* docs searchable

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#724] opened 2016-07-19 22:28 UTC
These should be available:
- **IPC** → https://docs.perl6.org/language/ipc
- **MOP** →https://docs.perl6.org/language/mop

That's it, I think.

**Comment by tommystanton** [comment] 2016-07-19 22:46
Thanks, @AlexDaniel (I had mentioned "IPC" in #723)! :smile:

**Comment by Altai-man** [comment] 2016-07-19 22:56
Closed with https://github.com/perl6/doc/commit/5c268237055ad7d58ba3bfb6be161d5000cc5b93?

**Comment by AlexDaniel** [comment] 2016-07-20 01:36
@Altai-man yeah. Kinda. Looking at it, I realize that it would've been much better if it was pointing to [language/mop](https://docs.perl6.org/language/mop) directly instead of [language/mop#index-entry-MOP](https://docs.perl6.org/language/mop#index-entry-MOP).

Is there any easy way to do that?

**Comment by gfldex** [comment] 2016-07-20 02:36
`index-entry-` is added automatically to prevent clashes between index anchor ids and heading anchor ids.

**Comment by gfldex** [comment] 2016-07-20 02:38
Well, there are two special cases hardcoded in `template/search_template.js` already. And if you really really want to you could add more. That may have consequences for your immortal soul tho.

**Comment by Altai-man** [comment] 2016-07-20 10:22
@AlexDaniel according to what gfldex said, we can do that(even I can do that) by hardcoding. But hardcoding is obviously not cool and I don't have intentions to do that.
As a long-term solution we can, of course, remove `index-entry-` and then by ourselves look for duplicate ids by some test.
If you want, you can make hardcoding by yourself, but, as for me, I doubt it matters.

**Comment by AlexDaniel** [comment] 2016-07-20 16:58
¯\\\_(ツ)\_/¯

Of course it's not cool, but at the same time a link that does not point you to the start of a page (when it should do so) is less than awesome.

Should we just close this or wait for some better solution to come?

**Comment by AlexDaniel** [comment] 2016-07-20 17:03
For example, we can have a special file with alternative queries. There we can make it so that typing “MOP” is equivalent to typing Meta-Object Protocol. Who knows, maybe it is going to be very common?

Another solution is to add MOP to our glossary (notice that it is already linked from [MoarVM](https://docs.perl6.org/language/glossary#MoarVM_)), there we can provide a link to language/mop. This, however, will require additional mouse click, which is not cool.

**Comment by Altai-man** [comment] 2016-07-20 18:29
Hmmm.

I think, that this issue as it states "Make abbreviations searchable" is done(LTA, but still better that nothing to search).

If we need special file or glossary item(both is good as for me), then we need to rename the issue or close this/open new. Probably, renaming will be slightly better.

**Comment by AlexDaniel** [comment] 2016-07-30 07:46
That's a LHF now :)

**Comment by AlexDaniel** [comment] 2016-09-29 21:32
Don't forget about **OOP**.

**Comment by Altai-man** [comment] 2016-09-29 22:31
Oh God, is it still open? I thought it was closed months ago...
Now I don't sure if I should fix/close it or wait for someone in terms of hacktoberfest.

**Comment by AlexDaniel** [comment] 2016-09-30 02:09
… what is hacktoberfest?

**Comment by coke** [comment] 2016-12-02 19:22
More months have passed.

What is the specific issue that is left? Let's create a ticket for that, we can reference this one, and close it.

**Comment by AlexDaniel** [comment] 2016-12-02 19:34
- [ ] OOP ?

The actual problem that is left is that MOP points to https://docs.perl6.org/language/mop#index-entry-MOP instead of just https://docs.perl6.org/language/mop, but I'm not sure if that is a problem.

**Closed** 2016-12-02 20:02 UTC
Labels: Hacktoberfest, LHF, search

**Comment by Altai-man** [comment] 2016-12-02 20:05
The issue is old and easy, therefore closed with the latest commit.
Feel free to open a new issue if `index-entry` thing needs discussing.
