### ISSUE TITLE
Every page starting with ? points to index.

### ISSUE THREAD

**Issue by jjatria** [perl6/doc#2270] opened 2018-08-16 22:00 UTC
## The problem

When browsing [the index for routines](https://docs.perl6.org/routine.html), the [`???`](https://docs.perl6.org/routine/???) routine links to the same page as [`?? !!`](https://docs.perl6.org/routine/??%20!!), which does not appear to actually include any information about what `???` might do. In fact, the `???` string does not appear in the linked page.

## Suggestions

These should either link to different pages, or, if they are different flavours of the same, the code example should be expanded to show both cases.

**Comment by JJ** [comment] 2018-08-20 10:44
In fact, that should point to [this page](https://docs.perl6.org/routine/%3F%3F%3F)

**Comment by JJ** [comment] 2018-08-20 10:48
I think it's a problem in the generation of the index. `?` is simply the start of the query section of an URL; anything starting with that points to `index.html`, which curiously enough we do have in our set of pages. It would return a 404 otherwise.
I'll see what can be done about this. Thanks for the report.

**Comment by JJ** [comment] 2018-08-24 17:33
Finally, I'm closing the PR (thanks to @Altai-man for reviewing it) that kinda patched (or maybe not) this problem.
This problem is related to how indexes (indices, whatever) are generated. The problem is that, for no reason, they are generated on the fly as POD6 and then put it back as HTML. This involves some back-and-forthing of MIME-encoded URLs, in whose steps some stuff is lost.
I think the main intention of this is to generate indices in the same template that the rest of the site. And this pass through pod6 is needed because the template *is embedded* in the pod-to-html code, as indicated in perl6/Pod-To-HTML#35
So.
I think the best approach is to be able to generate HTML pages directly without the bridge. And in order to to that we need to separate the template from the code, and then use that template to generate pages needed here (or simply create our own template). Then, we can refactor htmlify.p6 #1823 to use this.
So this becomes officially big, and also external. And it's the kind of issue we need to keep having. Thanks, @jjatria for reporting it.

**Closed** 2019-09-01 07:39 UTC
Labels: big, bug, external, meta, search
