### ISSUE TITLE
ToC show/hide animation is gone, but the delay is still there

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#686] opened 2016-07-10 11:44 UTC
[show]/[hide] buttons used to trigger a nice css animation, but it is no longer there.

However, the animation delay is still there. That is, you press [hide], then wait 1 second, and only then it actually hides.

**Comment by Altai-man** [comment] 2016-07-10 12:17
Does https://github.com/perl6/doc/pull/687 will fix the problem? If yes, merge it please.

**Comment by AlexDaniel** [comment] 2016-07-10 12:33
If I'm not mistaken, your pull request removes the animation completely. However, another fix would be to fix the animation.

Do we want the animation to be there or not?

**Comment by gfldex** [comment] 2016-07-10 12:36
CSS animations are fine in my eyes because the reader can make them go away with a userstyle. The less javascript we got the better. A botched setInterval can drain a battery rather quickly.

**Comment by Altai-man** [comment] 2016-07-10 12:45
Yes, you are right. I can revert js animation, firstly I thought title somewhat implies that delay should be removed.
If you want CSS animation as a substitution of js version, we can remove js version for now and create a ticket like "Implement css animation for ToC box". What do you think?
As for me, animation is unnecessary, but it doesn't bother me in any way if it's quick enough.

**Comment by gfldex** [comment] 2016-07-10 13:21
please remove the JS version

**Comment by zoffixznet** [comment] 2016-07-10 13:32
The show/hide feature was originally added as an easier way to get to content. Now that gfldex++ moved the ToC to the side, there's absolutely no reason for the existence of the show/hide feature and it should be yanked out entirely.

**Comment by AlexDaniel** [comment] 2016-07-10 13:41
> moved the ToC to the side, there's absolutely no reason for the existence of the show/hide feature and it should be yanked out entirely

And now I realized that it looks completely different on larger screens…

On a small screen the toc is still on the top, so [show]/[hide] feature still makes sense (or not?). Also, the links are blue, hmm…

**Comment by zoffixznet** [comment] 2016-07-10 13:44
> On a small screen the toc is still on the top, so [show]/[hide] feature still makes sense (or not?).

Oh, right, I forgot about smaller screens. I guess there is still use for it. The animation can likely be fixed by changing `ol` to `tbody` in here: https://github.com/perl6/doc/blob/master/html/js/main.js#L42 though I think there was a discussion above about removing the JS version.

**Comment by Altai-man** [comment] 2016-07-10 14:47
Now this situation looks more interesting.
So we have two choices:
1.Fix JS animation.
2.Remove JS animation and implement CSS animation(without state storing in the cookies) instead later.
I suppose, we can't throw away show/hide feature completely, because of small screens.
I can discard my pr or extend it to full removing of js part, but, I afraid, I can't make a css implementation, so new issue still will be created. And I can't decide what to choose by myself, since I'm quite a novice here.

**Comment by Altai-man** [comment] 2016-07-27 18:40
Closed by https://github.com/perl6/doc/pull/767

**Comment by Altai-man** [comment] 2016-07-27 21:53
It seems we should reopen this.

Current css animation doesn't affect height and based on font-size/padding/margin transformations. Due to this, element sizes are still the same. even if element is not visible. It's not really bad, but when someone uses a small screen, ToC moves to the page center and we have an empty space. It's bad.

The problem is: to animate show/hide, we need to know exact max-height of element(`auto` doesn't work). And this height is different for every page. Possible solutions are:
* Add some js to compute max-height and inject it into css every time(i.e. js+css variant, maybe it will be more efficient than js version).
* Throw away css animation and use js-animation.
* Throw away animation at all.

**Comment by gfldex** [comment] 2016-07-27 22:02
Animations on web pages have two functions. Convey time based information to the viewer simply be using progression of time. Guide the attention of the viewer to changed content.

There is no time based information to be conveyed. If you miss the fact that the ToC just disappeared, no amount of animation will help you. Also, we don't got viewers, we got readers. Reading and animations don't mix.

I'm a big fan of form follows function. If you can show me the function of that animation I'm happy to fix it.

**Comment by Altai-man** [comment] 2016-07-27 22:05
I suppose, we should switch to js-animation for now, since it's bugless(or better than current css-solution anyway) and open issue like "Create a cool and free and better css-animation" in case if some css-priest/magician(or just someone better than me) will be here looking for a work.

**Comment by Altai-man** [comment] 2016-08-01 23:36
Finally closed with https://github.com/perl6/doc/commit/d0dfc5ab6f6f5a3f3fe58a14e2e2d16f8f8b846c

**Closed by Altai-man** 2016-08-01 23:36 UTC
Labels: site
