### ISSUE TITLE
Explain ~ in regexes

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1008] opened 2016-11-14 01:06 UTC
It is something for balanced brackets, not completely sure how it works:
```perl6
say ‘(foo bar baz)’ ~~ /‘(’ ~ ‘)’ .*/  # ｢(foo bar baz)｣
```

**Comment by Altai-man** [comment] 2016-12-21 21:17
It has nothing to do with braces! This is another example:
```
m: say "Q ♥meows♥" ~~ /Q \s+ $<char>=. ~ $<char> $<stuff>=.+?/;
```
Here is a description from a duplicate issue:
`We can use "~" in form "delitimer1 ~ delmiter2 thing-in-between", but we don't have it documented.`

**Comment by Altai-man** [comment] 2017-02-12 13:57
I just noticed it is actually a duplicate of https://github.com/perl6/doc/issues/853.
We need to quickly document it before there are no new tickets about this issue!
Closed as a duplicate.

**Closed by Altai-man** 2017-02-12 13:57 UTC
Labels: docs
