### ISSUE TITLE
can't load infix // page from search box

### ISSUE THREAD

**Issue by jsoref** [perl6/doc#583] opened 2016-06-10 15:49 UTC
1. visit http://doc.perl6.org/ or http://localhost:3000/ (if you're using `make run`)
2. enter `//` in the search box
3. Select `//` under `Infix`

You'll get
http://doc.perl6.org/routine/%2F%2F which is 404
or
http://localhost:3000/routine///.html.html.html.html.html.html.html.html.html.html.html.html.html.html.html.html.html.html.html.html.html
which I was trying to fix as #576.

**Comment by peschwa** [comment] 2016-06-10 15:52
Dupe of #155.

**Closed by peschwa** 2016-06-10 15:52 UTC
