### ISSUE TITLE
≅, =~= and $*TOLERANCE

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#601] opened 2016-06-17 00:56 UTC
Tests: https://github.com/perl6/roast/blob/master/S03-operators/relational.t#L211
Some discussion: http://irclog.perlgeek.de/perl6/2016-06-17#i_12680850

**Comment by MasterDuke17** [comment] 2016-07-01 15:01
PR #604 added some documentation. I had some new tests written, but they need refinement after the expected behavior of $*TOLERANCE was cleared up.

**Comment by AlexDaniel** [comment] 2016-07-01 15:28
Oh, so we **do** have the documentation now. The only problem is that ``≅`` is not searchable.

As for the tests, please open a separate issue in roast repo.

**Comment by coke** [comment] 2016-12-28 19:44
I just double checked, ≅ is searchable on docs.perl6.org. Since that was listed as the last issue, closing ticket.

**Closed by coke** 2016-12-28 19:44 UTC
Labels: docs, search
