### ISSUE TITLE
<( and )> are not findable / poorly / not documented

### ISSUE THREAD

**Issue by lizmat** [perl6/doc#1048] opened 2016-12-11 21:56 UTC
See discussion between lizmat and psch starting at https://irclog.perlgeek.de/perl6/2016-12-11#i_13722101

**Comment by Altai-man** [comment] 2016-12-12 07:42
Duplicate of https://github.com/perl6/doc/issues/462?

**Comment by AlexDaniel** [comment] 2016-12-12 09:00
Yes.

**Closed by AlexDaniel** 2016-12-12 09:00 UTC
