### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ccworld1000** [perl6/doc#1910] opened 2018-04-08 15:15 UTC
CC $ **sudo** make
Password:
pod2onepage --threads=1 -v --source-path=./doc --exclude=404.pod6,/.git > html/perl6.xhtml
processed ./doc/HomePage.pod6 (cached)
processed ./doc/Language/5to6-nutshell.pod6 (cached)
processed ./doc/Language/5to6-perlfunc.pod6 (cached)
processed ./doc/Language/5to6-perlop.pod6 (cached)
processed ./doc/Language/5to6-perlsyn.pod6 (cached)
processed ./doc/Language/5to6-perlvar.pod6 (cached)
processed ./doc/Language/about.pod6 (cached)
processed ./doc/Language/classtut.pod6 (cached)
processed ./doc/Language/community.pod6 (cached)
processed ./doc/Language/concurrency.pod6 (cached)
processed ./doc/Language/containers.pod6 (cached)
processed ./doc/Language/contributors.pod6 (cached)
processed ./doc/Language/control.pod6 (cached)
processed ./doc/Language/enumeration.pod6 (cached)
processed ./doc/Language/exceptions.pod6 (cached)
processed ./doc/Language/experimental.pod6 (cached)
processed ./doc/Language/faq.pod6 (cached)
processed ./doc/Language/functions.pod6 (cached)
processed ./doc/Language/glossary.pod6 (cached)
processed ./doc/Language/grammar_tutorial.pod6 (cached)
processed ./doc/Language/grammars.pod6 (cached)
processed ./doc/Language/haskell-to-p6.pod6 (cached)
processed ./doc/Language/io-guide.pod6 (cached)
processed ./doc/Language/io.pod6 (cached)
processed ./doc/Language/ipc.pod6 (cached)
processed ./doc/Language/list.pod6 (cached)
processed ./doc/Language/module-packages.pod6 (cached)
processed ./doc/Language/modules-core.pod6 (cached)
processed ./doc/Language/modules-extra.pod6 (cached)
processed ./doc/Language/modules.pod6 (cached)
processed ./doc/Language/mop.pod6 (cached)
processed ./doc/Language/nativecall.pod6 (cached)
processed ./doc/Language/objects.pod6 (cached)
processed ./doc/Language/operators.pod6 (cached)
processed ./doc/Language/packages.pod6 (cached)
processed ./doc/Language/performance.pod6 (cached)
processed ./doc/Language/phasers.pod6 (cached)
processed ./doc/Language/pod.pod6 (cached)
processed ./doc/Language/pragmas.pod6 (cached)
processed ./doc/Language/py-nutshell.pod6 (cached)
processed ./doc/Language/quoting.pod6 (cached)
processed ./doc/Language/rb-nutshell.pod6 (cached)
processed ./doc/Language/regexes.pod6 (cached)
processed ./doc/Language/setbagmix.pod6 (cached)
processed ./doc/Language/subscripts.pod6 (cached)
processed ./doc/Language/syntax.pod6 (cached)
processed ./doc/Language/tables.pod6 (cached)
processed ./doc/Language/terms.pod6 (cached)
processed ./doc/Language/testing.pod6 (cached)
processed ./doc/Language/traps.pod6 (cached)
processed ./doc/Language/typesystem.pod6 (cached)
processed ./doc/Language/unicode.pod6 (cached)
processed ./doc/Language/unicode_ascii.pod6 (cached)
processed ./doc/Language/unicode_entry.pod6 (cached)
processed ./doc/Language/variables.pod6 (cached)
processed ./doc/Programs/01-debugging.pod6 (cached)
processed ./doc/Programs/02-reading-docs.pod6 (cached)
processed ./doc/Type/AST.pod6 (cached)
processed ./doc/Type/Any.pod6 (cached)
processed ./doc/Type/Array.pod6 (cached)
processed ./doc/Type/Associative.pod6 (cached)
processed ./doc/Type/Attribute.pod6 (cached)
processed ./doc/Type/Backtrace.pod6 (cached)
processed ./doc/Type/Backtrace/Frame.pod6 (cached)
processed ./doc/Type/Bag.pod6 (cached)
processed ./doc/Type/BagHash.pod6 (cached)
processed ./doc/Type/Baggy.pod6 (cached)
processed ./doc/Type/Blob.pod6 (cached)
processed ./doc/Type/Block.pod6 (cached)
processed ./doc/Type/Bool.pod6 (cached)
processed ./doc/Type/Buf.pod6 (cached)
processed ./doc/Type/CallFrame.pod6 (cached)
processed ./doc/Type/Callable.pod6 (cached)
processed ./doc/Type/Cancellation.pod6 (cached)
processed ./doc/Type/Capture.pod6 (cached)
processed ./doc/Type/Channel.pod6 (cached)
processed ./doc/Type/Code.pod6 (cached)
processed ./doc/Type/Complex.pod6 (cached)
processed ./doc/Type/ComplexStr.pod6 (cached)
processed ./doc/Type/Cool.pod6 (cached)
processed ./doc/Type/CurrentThreadScheduler.pod6 (cached)
processed ./doc/Type/Cursor.pod6 (cached)
processed ./doc/Type/Date.pod6 (cached)
processed ./doc/Type/DateTime.pod6 (cached)
processed ./doc/Type/Dateish.pod6 (cached)
processed ./doc/Type/Distro.pod6 (cached)
processed ./doc/Type/Duration.pod6 (cached)
processed ./doc/Type/Encoding.pod6 (cached)
processed ./doc/Type/Exception.pod6 (cached)
processed ./doc/Type/Failure.pod6 (cached)
processed ./doc/Type/FatRat.pod6 (cached)
processed ./doc/Type/Grammar.pod6 (cached)
processed ./doc/Type/Hash.pod6 (cached)
processed ./doc/Type/HyperWhatever.pod6 (cached)
processed ./doc/Type/IO.pod6 (cached)
processed ./doc/Type/IO/ArgFiles.pod6 (cached)
processed ./doc/Type/IO/CatHandle.pod6 (cached)
processed ./doc/Type/IO/Handle.pod6 (cached)
processed ./doc/Type/IO/Notification.pod6 (cached)
processed ./doc/Type/IO/Path.pod6 (cached)
processed ./doc/Type/IO/Path/Cygwin.pod6 (cached)
processed ./doc/Type/IO/Path/QNX.pod6 (cached)
processed ./doc/Type/IO/Path/Unix.pod6 (cached)
processed ./doc/Type/IO/Path/Win32.pod6 (cached)
processed ./doc/Type/IO/Pipe.pod6 (cached)
processed ./doc/Type/IO/Socket.pod6 (cached)
processed ./doc/Type/IO/Socket/Async.pod6 (cached)
processed ./doc/Type/IO/Socket/INET.pod6 (cached)
processed ./doc/Type/IO/Spec.pod6 (cached)
processed ./doc/Type/IO/Spec/Cygwin.pod6 (cached)
processed ./doc/Type/IO/Spec/QNX.pod6 (cached)
processed ./doc/Type/IO/Spec/Unix.pod6 (cached)
processed ./doc/Type/IO/Spec/Win32.pod6 (cached)
processed ./doc/Type/IO/Special.pod6 (cached)
processed ./doc/Type/Instant.pod6 (cached)
processed ./doc/Type/Int.pod6 (cached)
processed ./doc/Type/IntStr.pod6 (cached)
processed ./doc/Type/Iterable.pod6 (cached)
processed ./doc/Type/Iterator.pod6 (cached)
processed ./doc/Type/Junction.pod6 (cached)
processed ./doc/Type/Kernel.pod6 (cached)
processed ./doc/Type/Label.pod6 (cached)
processed ./doc/Type/List.pod6 (cached)
processed ./doc/Type/Lock.pod6 (cached)
processed ./doc/Type/Lock/Async.pod6 (cached)
processed ./doc/Type/Macro.pod6 (cached)
processed ./doc/Type/Map.pod6 (cached)
processed ./doc/Type/Match.pod6 (cached)
processed ./doc/Type/Metamodel/AttributeContainer.pod6 (cached)
processed ./doc/Type/Metamodel/C3MRO.pod6 (cached)
processed ./doc/Type/Metamodel/ClassHOW.pod6 (cached)
processed ./doc/Type/Metamodel/EnumHOW.pod6 (cached)
processed ./doc/Type/Metamodel/Finalization.pod6 (cached)
processed ./doc/Type/Metamodel/MROBasedMethodDispatch.pod6 (cached)
processed ./doc/Type/Metamodel/MethodContainer.pod6 (cached)
processed ./doc/Type/Metamodel/MultipleInheritance.pod6 (cached)
processed ./doc/Type/Metamodel/Naming.pod6 (cached)
processed ./doc/Type/Metamodel/Primitives.pod6 (cached)
processed ./doc/Type/Metamodel/PrivateMethodContainer.pod6 (cached)
processed ./doc/Type/Metamodel/RoleContainer.pod6 (cached)
processed ./doc/Type/Metamodel/Trusting.pod6 (cached)
processed ./doc/Type/Method.pod6 (cached)
processed ./doc/Type/Mix.pod6 (cached)
processed ./doc/Type/MixHash.pod6 (cached)
processed ./doc/Type/Mixy.pod6 (cached)
processed ./doc/Type/Mu.pod6 (cached)
processed ./doc/Type/NFC.pod6 (cached)
processed ./doc/Type/NFD.pod6 (cached)
processed ./doc/Type/NFKC.pod6 (cached)
processed ./doc/Type/NFKD.pod6 (cached)
processed ./doc/Type/Nil.pod6 (cached)
processed ./doc/Type/Num.pod6 (cached)
processed ./doc/Type/NumStr.pod6 (cached)
processed ./doc/Type/Numeric.pod6 (cached)
processed ./doc/Type/ObjAt.pod6 (cached)
processed ./doc/Type/Order.pod6 (cached)
processed ./doc/Type/Pair.pod6 (cached)
processed ./doc/Type/Parameter.pod6 (cached)
processed ./doc/Type/Perl.pod6 (cached)
processed ./doc/Type/Pod/Block.pod6 (cached)
processed ./doc/Type/Pod/Block/Code.pod6 (cached)
processed ./doc/Type/Pod/Block/Comment.pod6 (cached)
processed ./doc/Type/Pod/Block/Declarator.pod6 (cached)
processed ./doc/Type/Pod/Block/Named.pod6 (cached)
processed ./doc/Type/Pod/Block/Para.pod6 (cached)
processed ./doc/Type/Pod/Block/Table.pod6 (cached)
processed ./doc/Type/Pod/Heading.pod6 (cached)
processed ./doc/Type/Pod/Item.pod6 (cached)
processed ./doc/Type/Positional.pod6 (cached)
processed ./doc/Type/PositionalBindFailover.pod6 (cached)
processed ./doc/Type/Proc.pod6 (cached)
processed ./doc/Type/Proc/Async.pod6 (cached)
processed ./doc/Type/Promise.pod6 (cached)
processed ./doc/Type/Proxy.pod6 (cached)
processed ./doc/Type/PseudoStash.pod6 (cached)
processed ./doc/Type/QuantHash.pod6 (cached)
processed ./doc/Type/Range.pod6 (cached)
processed ./doc/Type/Rat.pod6 (cached)
processed ./doc/Type/RatStr.pod6 (cached)
processed ./doc/Type/Rational.pod6 (cached)
processed ./doc/Type/Real.pod6 (cached)
processed ./doc/Type/Regex.pod6 (cached)
processed ./doc/Type/Routine.pod6 (cached)
processed ./doc/Type/Scalar.pod6 (cached)
processed ./doc/Type/Scheduler.pod6 (cached)
processed ./doc/Type/Semaphore.pod6 (cached)
processed ./doc/Type/Seq.pod6 (cached)
processed ./doc/Type/Set.pod6 (cached)
processed ./doc/Type/SetHash.pod6 (cached)
processed ./doc/Type/Setty.pod6 (cached)
processed ./doc/Type/Signature.pod6 (cached)
processed ./doc/Type/Slip.pod6 (cached)
processed ./doc/Type/Stash.pod6 (cached)
processed ./doc/Type/Str.pod6 (cached)
processed ./doc/Type/Stringy.pod6 (cached)
processed ./doc/Type/Sub.pod6 (cached)
processed ./doc/Type/Submethod.pod6 (cached)
processed ./doc/Type/Supplier.pod6 (cached)
processed ./doc/Type/Supplier/Preserving.pod6 (cached)
processed ./doc/Type/Supply.pod6 (cached)
processed ./doc/Type/Tap.pod6 (cached)
processed ./doc/Type/Telemetry.pod6 (cached)
processed ./doc/Type/Telemetry/Instrument/Thread.pod6 (cached)
processed ./doc/Type/Telemetry/Instrument/Usage.pod6 (cached)
processed ./doc/Type/Telemetry/Period.pod6 (cached)
processed ./doc/Type/Telemetry/Sampler.pod6 (cached)
processed ./doc/Type/Thread.pod6 (cached)
processed ./doc/Type/ThreadPoolScheduler.pod6 (cached)
processed ./doc/Type/UInt.pod6 (cached)
processed ./doc/Type/Uni.pod6 (cached)
processed ./doc/Type/VM.pod6 (cached)
processed ./doc/Type/Variable.pod6 (cached)
processed ./doc/Type/Version.pod6 (cached)
processed ./doc/Type/Whatever.pod6 (cached)
processed ./doc/Type/WhateverCode.pod6 (cached)
processed ./doc/Type/WrapHandle.pod6 (cached)
processed ./doc/Type/X/AdHoc.pod6 (cached)
processed ./doc/Type/X/Anon/Augment.pod6 (cached)
processed ./doc/Type/X/Anon/Multi.pod6 (cached)
processed ./doc/Type/X/Assignment/RO.pod6 (cached)
processed ./doc/Type/X/Attribute/NoPackage.pod6 (cached)
processed ./doc/Type/X/Attribute/Package.pod6 (cached)
processed ./doc/Type/X/Attribute/Undeclared.pod6 (cached)
processed ./doc/Type/X/Augment/NoSuchType.pod6 (cached)
processed ./doc/Type/X/Bind.pod6 (cached)
processed ./doc/Type/X/Bind/NativeType.pod6 (cached)
processed ./doc/Type/X/Bind/Slice.pod6 (cached)
processed ./doc/Type/X/Caller/NotDynamic.pod6 (cached)
processed ./doc/Type/X/Channel/ReceiveOnClosed.pod6 (cached)
processed ./doc/Type/X/Channel/SendOnClosed.pod6 (cached)
processed ./doc/Type/X/Comp.pod6 (cached)
processed ./doc/Type/X/Composition/NotComposable.pod6 (cached)
processed ./doc/Type/X/Constructor/Positional.pod6 (cached)
processed ./doc/Type/X/ControlFlow.pod6 (cached)
processed ./doc/Type/X/ControlFlow/Return.pod6 (cached)
processed ./doc/Type/X/DateTime/TimezoneClash.pod6 (cached)
processed ./doc/Type/X/Declaration/Scope.pod6 (cached)
processed ./doc/Type/X/Declaration/Scope/Multi.pod6 (cached)
processed ./doc/Type/X/Does/TypeObject.pod6 (cached)
processed ./doc/Type/X/Eval/NoSuchLang.pod6 (cached)
processed ./doc/Type/X/Export/NameClash.pod6 (cached)
processed ./doc/Type/X/IO.pod6 (cached)
processed ./doc/Type/X/IO/Chdir.pod6 (cached)
processed ./doc/Type/X/IO/Chmod.pod6 (cached)
processed ./doc/Type/X/IO/Copy.pod6 (cached)
processed ./doc/Type/X/IO/Cwd.pod6 (cached)
processed ./doc/Type/X/IO/Dir.pod6 (cached)
processed ./doc/Type/X/IO/DoesNotExist.pod6 (cached)
processed ./doc/Type/X/IO/Link.pod6 (cached)
processed ./doc/Type/X/IO/Mkdir.pod6 (cached)
processed ./doc/Type/X/IO/Move.pod6 (cached)
processed ./doc/Type/X/IO/Rename.pod6 (cached)
processed ./doc/Type/X/IO/Rmdir.pod6 (cached)
processed ./doc/Type/X/IO/Symlink.pod6 (cached)
processed ./doc/Type/X/IO/Unlink.pod6 (cached)
processed ./doc/Type/X/Inheritance/NotComposed.pod6 (cached)
processed ./doc/Type/X/Inheritance/Unsupported.pod6 (cached)
processed ./doc/Type/X/Method/InvalidQualifier.pod6 (cached)
processed ./doc/Type/X/Method/NotFound.pod6 (cached)
processed ./doc/Type/X/Method/Private/Permission.pod6 (cached)
processed ./doc/Type/X/Method/Private/Unqualified.pod6 (cached)
processed ./doc/Type/X/Mixin/NotComposable.pod6 (cached)
processed ./doc/Type/X/NYI.pod6 (cached)
processed ./doc/Type/X/NoDispatcher.pod6 (cached)
processed ./doc/Type/X/Numeric/Real.pod6 (cached)
processed ./doc/Type/X/OS.pod6 (cached)
processed ./doc/Type/X/Obsolete.pod6 (cached)
processed ./doc/Type/X/OutOfRange.pod6 (cached)
processed ./doc/Type/X/Package/Stubbed.pod6 (cached)
processed ./doc/Type/X/Parameter/Default.pod6 (cached)
processed ./doc/Type/X/Parameter/MultipleTypeConstraints.pod6 (cached)
processed ./doc/Type/X/Parameter/Placeholder.pod6 (cached)
processed ./doc/Type/X/Parameter/Twigil.pod6 (cached)
processed ./doc/Type/X/Parameter/WrongOrder.pod6 (cached)
processed ./doc/Type/X/Phaser/Multiple.pod6 (cached)
processed ./doc/Type/X/Phaser/PrePost.pod6 (cached)
processed ./doc/Type/X/Placeholder/Block.pod6 (cached)
processed ./doc/Type/X/Placeholder/Mainline.pod6 (cached)
processed ./doc/Type/X/Pod.pod6 (cached)
processed ./doc/Type/X/Proc/Async.pod6 (cached)
processed ./doc/Type/X/Proc/Async/AlreadyStarted.pod6 (cached)
processed ./doc/Type/X/Proc/Async/CharsOrBytes.pod6 (cached)
processed ./doc/Type/X/Proc/Async/MustBeStarted.pod6 (cached)
processed ./doc/Type/X/Proc/Async/OpenForWriting.pod6 (cached)
processed ./doc/Type/X/Proc/Async/TapBeforeSpawn.pod6 (cached)
processed ./doc/Type/X/Proc/Unsuccessful.pod6 (cached)
processed ./doc/Type/X/Promise/CauseOnlyValidOnBroken.pod6 (cached)
processed ./doc/Type/X/Promise/Vowed.pod6 (cached)
processed ./doc/Type/X/Redeclaration.pod6 (cached)
processed ./doc/Type/X/Role/Initialization.pod6 (cached)
processed ./doc/Type/X/Seq/Consumed.pod6 (cached)
processed ./doc/Type/X/Sequence/Deduction.pod6 (cached)
processed ./doc/Type/X/Signature/NameClash.pod6 (cached)
processed ./doc/Type/X/Signature/Placeholder.pod6 (cached)
processed ./doc/Type/X/Str/Numeric.pod6 (cached)
processed ./doc/Type/X/StubCode.pod6 (cached)
processed ./doc/Type/X/Syntax.pod6 (cached)
processed ./doc/Type/X/Syntax/Augment/WithoutMonkeyTyping.pod6 (cached)
processed ./doc/Type/X/Syntax/Comment/Embedded.pod6 (cached)
processed ./doc/Type/X/Syntax/Confused.pod6 (cached)
processed ./doc/Type/X/Syntax/InfixInTermPosition.pod6 (cached)
processed ./doc/Type/X/Syntax/Malformed.pod6 (cached)
processed ./doc/Type/X/Syntax/Missing.pod6 (cached)
processed ./doc/Type/X/Syntax/NegatedPair.pod6 (cached)
processed ./doc/Type/X/Syntax/NoSelf.pod6 (cached)
processed ./doc/Type/X/Syntax/Number/RadixOutOfRange.pod6 (cached)
processed ./doc/Type/X/Syntax/P5.pod6 (cached)
processed ./doc/Type/X/Syntax/Regex/Adverb.pod6 (cached)
processed ./doc/Type/X/Syntax/Regex/SolitaryQuantifier.pod6 (cached)
processed ./doc/Type/X/Syntax/Reserved.pod6 (cached)
processed ./doc/Type/X/Syntax/Self/WithoutObject.pod6 (cached)
processed ./doc/Type/X/Syntax/Signature/InvocantMarker.pod6 (cached)
processed ./doc/Type/X/Syntax/Term/MissingInitializer.pod6 (cached)
processed ./doc/Type/X/Syntax/UnlessElse.pod6 (cached)
processed ./doc/Type/X/Syntax/Variable/Match.pod6 (cached)
processed ./doc/Type/X/Syntax/Variable/Numeric.pod6 (cached)
processed ./doc/Type/X/Syntax/Variable/Twigil.pod6 (cached)
processed ./doc/Type/X/Temporal.pod6 (cached)
processed ./doc/Type/X/Temporal/InvalidFormat.pod6 (cached)
processed ./doc/Type/X/TypeCheck.pod6 (cached)
processed ./doc/Type/X/TypeCheck/Assignment.pod6 (cached)
processed ./doc/Type/X/TypeCheck/Binding.pod6 (cached)
processed ./doc/Type/X/TypeCheck/Return.pod6 (cached)
processed ./doc/Type/X/TypeCheck/Splice.pod6 (cached)
processed ./doc/Type/X/Undeclared.pod6 (cached)
processed ./doc/Type/atomicint.pod6 (cached)
processed ./doc/Type/nativeInt.pod6 (cached)
processed ./doc/Type/utf8.pod6 (cached)
found duplicate index entry is (inheritance) at #i45 #i679
found duplicate index entry :{} at #i853 #i855
found duplicate index entry sym at #i260 #i263
found duplicate index entry «=» at #i430 #i765
found duplicate index entry compunit at #i273 #i274 #i275
found duplicate index entry increment operator at #i361 #i365
found duplicate index entry control flow at #i53 #i54 #i55 #i56 #i58 #i60 #i61 #i65 #i68 #i69 #i71 #i74 #i75 #i76 #i77 #i78 #i79 #i80 #i81
found duplicate index entry ++ at #i360 #i364
found duplicate index entry decrement operator at #i363 #i366
found duplicate index entry NFG at #i214 #i851
found duplicate index entry ∅ at #i628 #i733
found duplicate index entry prefix &amp; at #i129 #i871
found duplicate index entry declarator regex at #i258 #i594
found duplicate index entry $*USAGE at #i147 #i836
found duplicate index entry invocant at #i39 #i498
ATOMDIR="./highlights/atom-language-perl6";  \
	if [ -d "$ATOMDIR" ]; then (cd "$ATOMDIR" && git pull); \
	else git clone https://github.com/perl6/atom-language-perl6 "$ATOMDIR"; \
	fi; cd highlights; npm install .
Already up-to-date.
npm WARN package.json perl6-highlights@1.0.0 No README data
npm WARN package.json perl6-highlights@1.0.0 homepage field must start with a protocol.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
./app.pl assets
**perl6 htmlify.p6 --parallel=1**
Initializing ...
===SORRY!===
QAST::Block with cuid 25 has not appeared
make: *** [htmlify] Error 1
CC $

**Comment by JJ** [comment] 2018-04-08 15:45
That's a new one. You probably shouldn't use sudo, but I don't think that's
got anything to do with that.

What's the perl6 version?

**Comment by JJ** [comment] 2018-04-08 18:00
Let me check that. It looks like an error in a version of a particular package.

**Comment by JJ** [comment] 2018-04-08 18:34
Oops, closed by mistake.

**Comment by ccworld1000** [comment] 2018-04-09 01:15
CC $perl6 -v
This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.
CC $



I used the # **sudo make**  and # **make** at the same time

**Comment by JJ** [comment] 2018-04-09 05:11
You mean you get a different error if you use sudo make than if you use
make?

**Comment by JJ** [comment] 2018-04-09 05:12
On the other hand, you would be using two different versions of perl6 if
you are doing it via user or sudo.

**Comment by JJ** [comment] 2018-04-09 05:40
Apparently the second problem is due to [having an old version of LWP::Simple](https://github.com/perl6/perl6-pod-to-bigpage/issues/1). The first one is probably also due to a similar problem. Let's focus on the `make` one, without sudo. Please try and do 

    zef install --deps-only .

in the main directory of perl6/docs. If that does not reinstall the existing modules, please try and find out the versions of them you are using and get back to us.

**Comment by JJ** [comment] 2018-04-09 06:33
The versions of perl are the same, but maybe the module versions are not.
Re-installing LWP::Simple might fix that. Can you try the latest version of
that?

**Comment by ccworld1000** [comment] 2018-04-09 06:45
i trying

**Comment by ccworld1000** [comment] 2018-04-09 06:56
I use "LWP::Simple:ver<0.097>:auth<Cosimo Streppone>" get the same results

**Comment by ccworld1000** [comment] 2018-04-09 07:01
Do you usually use those convenient chat tools?

It's too inconvenient to communicate through [github issues]

**Comment by JJ** [comment] 2018-04-09 07:14
I'm jjmerelo in Telegram and Twitter, in case you want to use that. I am
also often in the #perl6 IRC channel.

**Comment by JJ** [comment] 2018-04-09 07:24
Anyway. Baseline is, I can't reproduce your error, so it must be due to some module and/or Perl version. Perl 6 2018.01 should be OK, so it must be some module that has not been updated for some time. Since rakudobrew forgets all installed modules, if you upgrade to 2018.03 and reinstall the modules with `zef` it might fix the problem. If it does not, please get back to us again, since it might be some OSX specific thing, since #1828

**Comment by ccworld1000** [comment] 2018-04-09 07:42
Many chatting tools can't be used in many things in China

**Comment by JJ** [comment] 2018-04-09 07:52
Tell me which one... Or just email, if you prefer that.

**Comment by ccworld1000** [comment] 2018-04-09 07:59
QQ is popular in China. I don't know if you can use it there.
my QQ Noumber is 2291108617

**Comment by JJ** [comment] 2018-04-09 08:01
I'll give it a try...

**Comment by JJ** [comment] 2018-04-09 08:05
Can't do. The only platform it seems to be available for and that I use is
Android, and I really prefer not to do these things using my thumbs. I'm
going to try WeChat.

**Comment by ccworld1000** [comment] 2018-04-09 08:07
This tool has been developing for many years in China. It has been super powerful. If you are used to it, you can build a discussion group or group through this tool. The efficiency is very efficient

**Comment by ccworld1000** [comment] 2018-04-09 08:08
WeChat can also, but it has no such function, which is equivalent to a streamlined version.

**Comment by ccworld1000** [comment] 2018-04-09 08:11
![cc](https://user-images.githubusercontent.com/22360168/38486738-7d1a4862-3c10-11e8-841e-2cc41637bf71.jpg)
You can add me in the form of WeChat scan two-dimensional code.

**Comment by JJ** [comment] 2018-04-09 08:13
OK, done, but I can only use it from the phone. Not ideal...

**Comment by JJ** [comment] 2018-04-09 08:52
After talking for a while, looks like it's a Pod::To::BigPage error, and more precisely the one posted in perl6/perl6-pod-to-bigpage#1 It's better if this issue is closed, and that one reopened with the new information.

**Comment by zoffixznet** [comment] 2018-04-09 16:49
I had the same crash with an earlier Rakudo, but upgrading to 2018.03 resolved the issue.

I've also just now had a build of 2017.11 rakudo with all the latest modules, and the same error occurred, so I doubt it's just some module that's problematic.

There's no Rakudo Star newer than 2018.01 yet (next one will be 2018.04, due in 4-5 weeks), but if you want you could try [building compiler-only from source](http://perl6.org:4242/files/rakudo/source)

**Comment by JJ** [comment] 2018-04-12 15:56
@ccworld1000 can you please upgrade to 2018.03 and see if that fixes the issue?

**Comment by JJ** [comment] 2018-04-16 18:16
@ccworld1000 did you try and use 2018.03? You can download and build it from source, for instance

**Comment by JJ** [comment] 2018-04-24 16:28
There's no response fromp the OP, and a solution has been suggested, so I'm closing this issue. Please feel free to reopen it if you think it deserves more attention.

**Comment by AlexDaniel** [comment] 2018-04-24 16:34
Well the issue was opened just 16 days ago, and if I got it right there was an issue with the latest rakudo star? We don't have a 2018.04 star yet (not even 2018.04 rakudo release actually), so this issue is probably not resolved yet. At the very least I'd much rather hear something from the OP.

**Comment by JJ** [comment] 2018-04-24 16:39
Wouldn't the next Rakudo * be 2018.05?

**Comment by zoffixznet** [comment] 2018-04-24 16:40
No, it's Jan, Apr, Jul, and Oct.

**Comment by AlexDaniel** [comment] 2018-04-24 16:41
Typically it's .01, .04, .07 & .10

**Comment by JJ** [comment] 2018-04-24 16:46
Ah, OK. Great. Let's wait for the answer from the OP and/or the new version.

**Comment by bazzaar** [comment] 2018-05-08 13:30
Hi, while 'make install' of Rakudo Star 2018.04, I noticed p6doc 'FAIL - proceeding with force install' or something like that. Rakudo Star installed correctly, and zef subsequntly installed cro and dependencies without a problem. So I thought I'd try to install and make a local copy of the docs, to test the above issue, and found that 'make html' from within the doc directory fails.

[make_p6doc_html.txt](https://github.com/perl6/doc/files/1984047/make_p6doc_html.txt)

Is this the same problem that the OP reported?

bazzaar

**Comment by JJ** [comment] 2018-05-08 18:51
I'm looking at it, and I think the problem has something to do with some node module, which is used for highlighting. There are some warnings related to coffeescript, which should have been fixed. 
That is in the same ballpark as this particular issue, but it's a different one altogether. I would be very grateful if you would open a new issue, indicating all the particulars. In fact, if there's no response from the OP, I'm assuming this issue has been solved and will close it.

**Comment by JJ** [comment] 2018-05-09 06:39
I assume this problem has been solved with the new version. If it's not, please reopen and add the new error message.

**Closed by JJ** 2018-05-09 06:39 UTC
Labels: JJ TPF Grant, build
