### ISSUE TITLE
P6-101 refers to Perl 5 – it shouldn't because it's not a 5to6 doc

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2191] opened 2018-07-20 11:04 UTC
It goes like this:

> Other programming languages call that a hash table, dictionary, or map

↑ that is fine, these are commonly used terms. Next sentence:

> You can query a hash table for the value that corresponds to a certain $key with %hash{$key}[1].

First of all, footnotes should not be used near code because `[1]` can look like a perl 6 syntax. Either way, what's in that footnote? (as a perl 6 beginner I'm interested!)

>  [↑] Unlike Perl 5, in Perl 6 the sigil does not change when accessing an array or hash with [ ] or { }. This is called sigil invariance

Perl 5? Sigil invariance? Why am I presented with all that?

----

Now that I look at it, I think the whole document should reclassified as 5to6-101. For example:

> Every Perl 6 program should begin with use v6;. This line tells the compiler which version of Perl the program expects. Should you accidentally run the file with Perl 5, you'll get a helpful error message.

↑ not exactly? I don't think it's common that someone would executed a `⌁.p6` document that has a perl6 shebang with perl5.

Assigning @JJ because he knows how to untangle stuff like this :)

**Comment by stmuk** [comment] 2018-07-20 11:46
The whole point of the document was to be an introductory document which wasn't a p5 to p6 guide see #2145 I'm not particularly worried by the occasional (historic) reference to perl 5 in it but I'm not opposed to anyone removing them. I'd be more opposed to moving it.

**Comment by JJ** [comment] 2018-07-20 15:36
@stmuk the problem is that the guidelines quite clearly specify that we shouldn't explain perl 6 in terms of P5, because people might not come from there, and in fact they don't in a sizeable percentage of the cases. I removed a few references (notably the first paragraph) but I guess I missed a few.
@AlexDaniel thanks for the confidence, I'm just back from Japan (typing this from CDG, in fact) so I guess I'll more or less back to normal now.

**Comment by stmuk** [comment] 2018-07-21 06:22
@JJ Yes I understand why people don't like Perl 5 references anymore (and note this is a change from the historic way of doing things) but just don't agree it's particularly useful advice in this case.

**Closed** 2018-08-12 08:12 UTC
Labels: docs, update
