### ISSUE TITLE
Instant.DateTime does not appear to be documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1120] opened 2017-01-05 19:45 UTC
Impl: https://github.com/rakudo/rakudo/blob/6d28c1d0e8593ed81e4dd55e6c4fdffeaad0771b/src/core/Instant.pm#L43

But not seeing it in https://docs.perl6.org/type/Instant

Haven't checked its presence in roast...

**Comment by coke** [comment] 2017-01-10 19:36
This is a duplicate of #1096

**Closed by coke** 2017-01-10 19:36 UTC
