### ISSUE TITLE
"my" page needs example of List Assignment

### ISSUE THREAD

**Issue by COMBORICO** [perl6/doc#1958] opened 2018-04-23 22:30 UTC
## Problem
https://docs.perl6.org/syntax/my
## Suggestions

my ($a, $b) = "apple", "bucket";

**Comment by W4anD0eR96** [comment] 2018-04-24 03:14
We have it, in fact. https://docs.perl6.org/language/variables#Declaring_a_list_of_variables

The problem is we talk about "list assignment" on both `my` and `our`, that cause none of them gather it into /syntax/*

**Comment by fluca1978** [comment] 2018-04-24 07:37
I've done some cross reference, if this is ok please close the issue.

**Comment by JJ** [comment] 2018-04-25 15:09
List assignment is totally independent of my, which is a scope declarator. Our can be rare or medium, but it's still got to be put in the documentation.

**Comment by COMBORICO** [comment] 2018-04-25 16:00
If the majority of the time list assignment is done with "my", how can you say it is totally independent?  Even if 50% of the time List Assignment is done used with other operators, that shows that "my" and List Assignment are deeply related.  I don't consider that independent.  

In fact, I consider List Assignment to be a shorthand version of "my", regardless if List Assignment is used with other faculties.  A user's first exposure to List Assignment, will likely be by way of "my".  To relegate List Assignment under the vast category of Variables to suit some technicality is a mistake.  The Docs should be about ease of use, not categorical pureness.  

I never said not to include "our" in the documentation.  Contrary, I said to include List Assignment examples for both "our" and "my".  And, it should also be in Variables, for that matter.

**Comment by fluca1978** [comment] 2018-04-26 06:33
> If the majority of the time list assignment is done with "my"

No, it's not. I believe you are confusing this shortcut:

```
  my ( $a, $b ) = ( 1, 2 );
```

with what you can really do:

```
  my ( $a, $b );
 ( $a, $b ) = ( 1, 2 );
```

so the point is not that `my` can be used in list assignment, but that it can handle list of variables.

> Contrary, I said to include List Assignment examples for both "our" and "my".

I believe we should not include as much examples as the one I already placed. Also to avoid people thinking that the _only_ way to assign lists is thru my, while they can obsviously do the following list assignment:

```
  my $a = 10;
  my $b = 20;
  ( $a, $b ) = ( $a * 10, $b * 20 );
```

which does not involves `my`.

**Comment by JJ** [comment] 2018-04-26 06:45
And I'm closing this issue. It asked to provide an example of list assignment, which it did, so I consider it solved. Thanks @fluca1978

**Closed by JJ** 2018-04-26 06:45 UTC
Labels: JJ TPF Grant, update

**Comment by COMBORICO** [comment] 2018-04-26 14:06
Fluca, you are correct.  I was confusing "my" with "=".  Regardless, I still feel the "my" page should mention List Assignment shortcut.
