### ISSUE TITLE
Cool part of List forms a nice landmine, document it all as traps

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#992] opened 2016-10-27 22:15 UTC
``` perl6
my @a = <a b c d>;
say @a.contains(‘c’);    # True
say @a.index(‘a’);       # 0
say @a.starts-with(‘a’); # True
```

**Comment by VynceMontgomery** [comment] 2016-10-28 02:41
I don't understand what about this is a trap.

**Comment by pmichaud** [comment] 2016-10-31 16:40
Each of the examples given does exactly what I would expect it to do... I'm also not sure how this is a landmine/trap.

**Comment by gfldex** [comment] 2016-11-01 10:25
see: https://irclog.perlgeek.de/perl6-dev/2016-10-27#i_13476643

The majority opinion seams to be no-trap. However, we do a poor job to explain the dynamic nature of Perl 6 in general. We don't even got a section in the docs to put such explanations.

**Comment by AlexDaniel** [comment] 2016-11-01 12:17
Actually, the majority opinion is that it is a trap indeed, hence the whole discussion about ways to solve it. For example, the first comment here clearly indicates that.

**Comment by pmichaud** [comment] 2016-11-01 16:08
Just as there are operators that coerce their operands to a specific type (e.g., &infix:<+>, &infix:<~>, &infix:<?&>), so there are (Cool) methods that treat their invocants as a specific type.  For example, @array.flip means something very different from @array.reverse .  And we eliminated ".length" altogether because of its inherent ambiguity, moving instead to .elems, .chars, .codes, etc.

So, .index implies "coerce to a string".  I don't know when .contains and .starts-with were added to Perl 6, but it seems clear to me that those were intended to be "stringy methods", and if I use them I expect them to treat their invocant as if they are a string.  That's just the way Perl 6 is designed to work.

Moving List out of Cool strikes me as all sorts of wrong -- having Lists (Arrays) automatically coerce into string or numbers as needed has always struck me as being one of the fundamental strengths of Perl.

Pm

**Comment by AlexDaniel** [comment] 2016-11-01 16:39
@pmichaud yea, great, but as far as I know there is no ticket yet where this discussion would be appropriate.

The point of this issue: you may accidentally use ``@a.contains($elem)`` and it may seem like it is working, but in reality it is a method that works on strings. Given that it's something that is not obvious (it's not ``.str-contains``, also List itself has no ``.list-contains``) and given that it may produce false results that are right *sometimes*, it is a trap which should be documented. The description of this trap may include justifications for such trapy behavior, that's fine. But please cut that “there is no problem” crap. Just because you are aware of this problem does not mean that everyone reading the docs knows about it too, and there is no reason to assume that they should magically know about these details.

And this applies to all other issues regarding traps. If your general idea is that Perl 6 is flawless and everyone who might think that ``@a.contains($stuff)`` does exactly what it says is so dumb that he doesn't deserve a little section in the documentation, that's fine. Just move on.

**Comment by VynceMontgomery** [comment] 2016-11-01 22:19
well, none of your examples are surprising, because all of your examples are the list acting like "contains" and "starts with" and "index" work the way they intuitively would with lists, so I didn't understand the problem. On the other hand, these look like traps: 

```
say <a b c d>.index("c"); # 4
say <a b c d>.contains("b c"); # True
say <a b c d>.starts-with("ab"); # False
```

and I would not have guessed any of this from your examples. I would expect -- and i think most people would expect -- lists to provide a function called something like "index" that returned the index of that value in the list. I would expect "contains" to be something like "has as sequential elements". I would expect "starts-with" to be "contains starting at index 0". The fact that these are not what these methods mean to a list is surprising. Your examples just happened to not show the surprising results.

**Comment by VynceMontgomery** [comment] 2016-11-01 22:29
in fact, is there a reason that `List.contains(Any $needle)` doesn't exist as `self (cont) $needle` ? etc... ?

**Comment by gfldex** [comment] 2016-11-15 10:30
my first shot at tackling this problem with 4088900919

**Comment by VynceMontgomery** [comment] 2016-12-04 23:06
I see that this change has been basically accepted, in a modifoed form. I may provide more feedback to the text for its own sake, but I also have some reservations about this commit as a fix for this problem. Basically, I don't think that the "trap" here is in not understanding how coercion works; I think the trap is that it is not clear that coercion happens because the names of the methods read like perfectly good methods to use on a list. So while this text may be good, it does not clear up the confusion of this particular situation.

**Comment by AlexDaniel** [comment] 2017-07-03 23:20
Wow, I just reread comments here… I guess I'm bad at conveying ideas, but others should really turn the volume of their “I know perl and I'll never make this mistake” speaker.

@VynceMontgomery++ for defining the problem precisely in one sentence.

**Comment by toolforger** [comment] 2017-07-04 09:17
I think the problem is that it's not obvious which of the methods convert to string (or number) and which don't.
People who've been around since these methods started to exist, the learning curve is easy and slow, and "of course" they know which method does what.
People who're new to Perl6 will have a large list of method names to learn at once. If they aren't specifically made aware that they need to learn by heart whether there's a conversion or not, they'll just assume (yeah I know it's bad, but you can't learn everything at once so you *must* assume at least a few things), then they'll form inconsistent ideas about what's really happening, and will fail.

**Comment by VynceMontgomery** [comment] 2017-07-04 22:16
I still think that's only part of the problem.  The fact that List.index is a perfectly valid concept (and extant in other languages) means that people will expect List.index to do what List.index ought to do. No-one has yet provided a reason it shouldn't. Similarly, List.contains and List.starts-with. Why not make them do the obvious thing for lists? And, until they do, make the documentation super clear that while yes, that's what you might expect, it's not what happens. 

Perl6 has no native speakers, yet, and this is not a holdover from Perl5. The community of people who are likely to be tripped up by this is everyone who comes to the language fresh; the community of people who will know that List doesn't natively .contain or .index is going to be a fraction of the people who have been with Perl6 since before this decision was made, i.e. much much smaller.

**Comment by AlexDaniel** [comment] 2017-07-04 22:33
That's an interesting thought, actually. I think most people will oppose the idea of .contains or .starts-with doing something different, me included. However, I wonder why these methods should work at all.

Has anybody ever used List.contains for some useful purpose? If this gave a warning, would somebody experienced even notice it?

**Comment by VynceMontgomery** [comment] 2017-07-04 22:55
Why would you be opposed to making List.contains do the obvious thing? 

(I do not think List should inherit part of Cool and disable other parts; that seems like madness. But making it do the obvious useful thing seems ... obviously useful.)

**Comment by AlexDaniel** [comment] 2017-07-04 23:04
Well, to put simply, .contains checks if a string exists in another string. That's it (right now). You are thinking about redefining that, which may or may not have a good justification, but I doubt it will become reality (not perl6-ish, each thing should do its own thing, etc.).

At the same time, ``@list.contains`` with the current implementation is just nonsense. It does not do what anybody wants, it is full of traps, there's *no reason for it not to be disabled*. May seem like madness, but at least we will get rid of the trap (without any drawbacks, unless somebody can name any).

**Comment by VynceMontgomery** [comment] 2017-07-05 00:11
I'm asking why you oppose it, not whether you think it will happen; "It won't happen" isn't a reason to oppose it, it's a prediction about whether your reason matters.

If your answer is "Not perl6-ish" I don't understand -- how is it not perl6ish? perl6 has lots of builtins that do the right things, and TIMTOWTDI. Having a method that is an English word that does notionally the same thing as an operator that is named an abbreviation *of that word* seems quite perl6ish. That's the argument for `.contains` working like `(cont)`; I feel the others flow naturally in a parallel way, though as far as I know there isn't a synonym of `.index` simpler than using `.first:p` and looking at the index in the pair. Also, it looks like `starts-with` is no longer supplied by Cool.

(Though, for even better parallelism with `String.contains`, `List.contains` could take a list and return true only if that list exists as a contiguous sublist.) 

To be clear, IMO the current implementation isn't nonsense; it's just not as sensible as making it be a synonym of the `(cont)` operator. 

"No reason for it not to be disabled" except that simply disabling it: 
   * provides no actual functionality
   * removes functionality (albeit of questionable value) that fits a predesignated paradigm, and
   * is a bit arbitrary. Where do you draw the line? The whole point of Cool is that it provides a fallback for a bunch of DWIM behaviors that are individually questionable; how would you decide which ones to keep? (substr a number? really? but that's literally the first example, so...)
So I would argue that disabling it is clearly not Perl6ish. 

Anyway, I don't see anybody objecting to making the documentation for contains explicit about the List traps on "contains" and "index", and, i guess, "rindex". "match" is already explicit about the coercion.

**Comment by AlexDaniel** [comment] 2017-07-05 00:33
> The whole point of Cool

is to have strings and numbers behave similarly when you need it. The fact that List is Cool is very unfortunate. I guess the main reason was that things like ``@a == 5`` should work, but the whole stringy part of Cool is totally worthless. In fact, even all of the trigonometry functions probably don't give anything useful, but at least there are no traps associated with them.

> To be clear, IMO the current implementation isn't nonsense

The implementation itself is not, but if somebody writes something like ``@a.contains(…)``, it is nonsense.

> I'm asking why you oppose it
OK, let's look at this code:
```perl6
$music.contains(‘foo’)
```
By redefining .contains the way you say, we will lose clarity here. And I don't think it's worth it.

**Comment by VynceMontgomery** [comment] 2017-07-06 00:31
"we will lose clarity" is not a complete description. What is unclear about it? We're going to look through `$music` to see if it *contains* `'foo'`.

**Comment by AlexDaniel** [comment] 2017-07-06 00:50
Sooo… an element or a substring? :)

**Comment by VynceMontgomery** [comment] 2017-07-06 01:13
Whichever is appropriate. I don't understand why you're saying that's unclear. Are you arguing all polymorphism is unclear?

**Comment by jnthn** [comment] 2017-07-06 09:18
It's a fairly clear Perl 6 design principle that operations have consistent semantics and coerce their operands. That's why we have `==` for numeric comparison and `eq` for string comparison, for example. In general, you can sensibly have dynamic types and operations with fixed semantics, or static types and operations with overloaded semantics based on type. Doing dynamic types with overloaded semantics based on type gets you unpredictable programs *even if you learned the language really well*.

**Comment by toolforger** [comment] 2017-07-06 12:20
The point here is the combination of lists and coercion creates inconsistencies.
Consider a list of lists; does `<<a> <b> <c> <d>>` contain `<b c>`? One would say it doesn't because it's a silly case, but then consistency would demand that `<'a' 'b' 'c' 'd'>` does not contain `'bc'`, but IIUC we want `'bc'` to to converted to `<'b' 'c'>` to make the comparison meaningful.

"Convert if it makes the operation meaningful" as a guiding principle doesn't work well for lists in general.
Consider appending. What should happen if you append `<1 2 3>` to `<5 'xy' Nil>`? Do we get `5 'xy' Nil 1 2 3>` or `<5 'xy' Nil <1 2 3>>`? Both would be consistent with any converting policy, and depending on the exact element types, one or the other interpretation could be "more natural".

My personal opinion is that for lists, particularly polymorphic ones, there's no clear guideline and the available functions need to be explicit about whether there's a conversion or not, because otherwise learners and coders will keep mispredicting the code's behaviour because there's no hard-and-fast rule.

I have seen a lot of solutions, working and nonworking alike, so I can elaborate if somebody is interested.

**Comment by pmichaud** [comment] 2017-07-06 14:27
On Thu, Jul 06, 2017 at 12:20:37PM +0000, Joachim Durchholz wrote:
> The point here is the combination of lists and coercion creates inconsistencies.

I've been following this thread off-and-on and feel like chiming in here.

Personally I don't think the problem is one of "lists and coercion"... because if that's the case then we can pretty much say "the problem is one of XXX and coercion" for many types.

I think the problem is that the phrase "contains" has overloaded meanings depending on whether we're looking at a string, list, bag, hash, whatever.  As Jonathan points out, using polymorphism in this case (i.e., Str.contains doing something entirely different from List.contains) is just replacing one set of traps for another, because I can never be entirely certain what C< $x.contains("foo") > is going to do.  

(Yes, this sort of ambiguity is often a desirable feature of polymorphism.  Not here.  And we've generally tried to sweep such ambiguities into a single place, such as smart matching, rather than let it be spread throughout CORE.)

In the past when this has happened (e.g., ".length", ".reverse"), our solution was to eliminate the ambiguous term in favor of adjectives that made the operation much more obvious/explicit ('.elems', '.chars', '.codes', '.flip', etc.).

Personally, I really dislike the notion of "contains" having a Stringy interpretation at all -- the word "contains" has more obvious connections to things that involve containers (lists, hashes, arrays, etc.) and not so much with strings.  

(Yes, I know that a string can be considered a container of characters (or codepoints).  But we also don't allow .[] on strings either, for similar reasons.  And even here stringy .contains isn't looking for membership of a single element, but rather a specific subsequence of elements.)

Things that other languages do to avoid this ambiguity:

   strstr
   instr
   findstr

I think the solution is to change stringy ".contains" to some other phrase, as opposed to trying to make the polymorphism work.

Pm

**Comment by VynceMontgomery** [comment] 2017-07-06 21:22
I would totally support that approach (though I've never liked the name "strstr").

**Comment by smls** [comment] 2017-08-19 14:27
I agree with @pmichaud:

* The Perl way of using differently named coercive routines for different behaviors (rather than going wild with polymorphism) is generally a good thing.
* However, to do that well, routine names have to be chosen very carefully to not mislead people.
* The name `.contains` was a dubious choice for what it does. *(And should maybe be deprecated or renamed in 6.d).*

And I would also add:
* `List` and `Map` being `Cool` was done for historical reasons (emulating Perl 5), and might not have been a good idea.
  * Stringy and numeric types sharing the same coercive methods has lots of utility and *doesn't* tend to be confusing in practice; `List` and `Map` being part of the mix is what tends to cause traps.
  * Looking at the things that `Cool` provides, I don't see much (if anything) that I would feel comfortable calling on a `List` or `Map` without explicit coercion for better code clarity. (Maybe `@foo.sqrt`, but eh.)
  * Other collection types (e.g. `Set`) aren't `Cool` simply because the historical reasons didn't apply to them, and they do fine without it.

**Comment by JJ** [comment] 2018-04-21 08:56
After all the commits related to this issue, would you consider it solved? What would remain to be done?

**Comment by AlexDaniel** [comment] 2018-04-21 09:02
I think it needs a list of things not to use (kinda, depending on context) with text like ≈“If you're working with lists, these methods will likely not do what you mean (as they will stringify your lists first): .contains, .index, .starts-with, …, …, …, …, …, …”

**Comment by AlexDaniel** [comment] 2018-04-21 09:06
↑ so that if a user is using let's say `.starts-with` and it acts weirdly (in their eyes), they can go to traps page and just ctrl+f for “starts-with”. In theory the documentation for `starts-with` should already have enough info, but right now it just says:

> Returns True if the invocant is identical to or starts with $needle.

If you connect the dots you'll clearly see why that happens, but having a useful entry on the traps page can be beneficial I think (more so if the general issue is discussed in depth and we will be able to link to it to explain the confusion).

**Closed** 2018-05-22 06:00 UTC
Labels: docs
