### ISSUE TITLE
create standard location for translated pages per language

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#2195] opened 2018-07-20 13:02 UTC
## The problem

Translations in languages other than en, e.g., cn, need their own directory.

And we have doc PR #2194, a Chinese translation, waiting in the wings.

## Suggestions

Look at GNU, Debian, and other projects to see their practices.

## UPDATE

Maybe this:

    doc/
        en/
            page404.pod6
            Language/
            ...duplicate current default English version under doc/
        cn/
        ...

**Comment by JJ** [comment] 2018-07-20 15:44
OK, I see what you mean.

The problem is that translated pages are hard to maintain or simply
impossible. We can't admit them into the repo and then leave them there to
bitrot forever. I think it was either @coke or @alexDaniel who mentioned
what was the long-term plan for READMEs. It's already difficult as it is to
maintain them. But whole translated pages would be a new game, and one in
which I am not sure I want to play.

So my vote would be on having those pages in some other repo, under the
responsability of whoever translates them. I'm sure it's excellent work,
but we have to look a bit more long-term here...

**Comment by JJ** [comment] 2018-07-22 11:05
We are going to discuss that, among other things, [in a Perl 6 doc BoF in Glasgow](http://act.perlconference.org/tpc-2018-glasgow/wiki?node=Perl6%20documentation%20BoF) If you are going to attend, please add your name to the list.

**Comment by JJ** [comment] 2018-07-24 08:17
Also, I am against changing the URL of current pages.

**Comment by coke** [comment] 2019-03-13 17:36
2¢

I think this would be much easier to address once we have a dynamic site instead of a static one, as then URLS could stay the same and show different content (or automatically redirect to a language specific URL)

If there's a serious effort to work on a translation, I'd rather have it be part of the project.

**Comment by moritz** [comment] 2019-05-03 20:47
@JJ did you discuss it at the BoF in Glasgow? If yes, what was the result?

**Comment by JJ** [comment] 2019-05-04 06:23
No, we didn't. I would be for closing this, since with current (scarce) resources it would be impossible to maintain translations. There haven't been any significant one, other than the Chinese, which is just a start.

**Closed** 2019-05-04 08:00 UTC
Labels: wishlist
