### ISSUE TITLE
Searching Str should point directly to the Str class

### ISSUE THREAD

**Issue by Skarsnik** [perl6/doc#2484] opened 2018-11-30 20:48 UTC
## The problem

Searching Str and hitting enter lead you to 'string literal' page since it's the first result starting with str. It should probably lead to Str

## Suggestions

When the case is specified by the user, probably goes to the matching class documentation

**Comment by JJ** [comment] 2018-12-01 08:01
That's a known issue: #1108. Kind of difficult to know, in every case, what would be the "correct" thing if you press enter...

**Comment by coke** [comment] 2019-03-13 16:45
Closing as a duplicate of #1108.

**Closed by coke** 2019-03-13 16:45 UTC
Labels: big, search, wishlist
