### ISSUE TITLE
searching index for single char things

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#756] opened 2016-07-25 02:40 UTC
like Z, R or S should be special cased so that the single char result is shown at the top of the list.

**Comment by AlexDaniel** [comment] 2016-07-25 02:43
What about implementing https://github.com/perl6/doc/issues/247 instead?

**Comment by coke** [comment] 2016-07-25 14:30
This ticket is a special case of #247, yes.

**Comment by coke** [comment] 2017-07-04 23:35
Closing as a dupe of #247.

**Closed by coke** 2017-07-04 23:35 UTC
Labels: search
