### ISSUE TITLE
http://doc.perl6.org/routine/spurt:  example lacks ':'

### ISSUE THREAD

**Issue by jkeenan** [perl6/doc#427] opened 2016-03-19 18:54 UTC
```perl6
$ perl6
> my $filename = 'enc_missing_colon.txt'
enc_missing_colon.txt
> say $filename, "latin1 text: äöüß", enc => 'latin1';
Unexpected named parameter 'enc' passed
> say $filename, "latin1 text: äöüß", :enc => "latin1";
enc_missing_colon.txtlatin1 text: äöüß(enc => True) => latin1
> exit
```
The example for use of ```:enc``` lacks a colon before ```enc```.

**Comment by timo** [comment] 2016-04-17 18:35
actually,

```
timo@schmand /tmp> perl6 -e 'spurt "test.txt", "latin1: äöüß", enc => "latin1"'
timo@schmand /tmp> cat test.txt 
latin1: ����⏎
timo@schmand /tmp> perl6 -e 'spurt "test2.txt", "latin1: äöüß", :enc => "latin1"'
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at -e line 1
```

**Comment by MadcapJake** [comment] 2016-04-17 18:35
@jkeenan this *does not* need a colon.  In your example, you see that you are actually concatenating something quite bizarre (say just concatenates all arguments)
`enc => 'latin1` will create a named pair and `say` doesn't accept any named arguments called `enc`.  So when you changed it to `:enc => 'latin1'` you actually are creating a named pair with a key that is a named pair:
`(enc => True) => 'latin1'`
Because functions can only take named pair arguments with string names, it just assumes you want to concatenate.

**Comment by timo** [comment] 2016-04-17 19:00
i should also point out that the issue is about the documentation of spurt and the example code in the initial comment is about say. spurt has the :enc parameter, whereas say doesn't. and say also doesn't take a filehandle as the first argument. That's probably where the confusion came from?

Anyway, with the commit reverted I'm going to close this issue again.

**Closed by timo** 2016-04-17 19:00 UTC
