### ISSUE TITLE
Partial Build [Possibly due to parallelization]

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#664] opened 2016-07-04 16:53 UTC
The screenshot below shows a partial build of the Language docs, even though [the build log](https://docs.perl6.org/build-log/build-2016-07-04T15:50+0000.log) shows them built. Visiting the missing pages directly gave a 404.

This issue may or may not have been caused by 8d83f42b857fb4725de552c16ffdf90df72e081f that added parallelzation. We undid it in d41f52ec5680ed140ccda17180049aa202875143 and the docs built fine.

Some more testing needs to be done with the parallelization feature turned on.

![lang](https://cloud.githubusercontent.com/assets/5747918/16566820/0987b978-41e6-11e6-8907-8493d77f720c.png)

**Comment by MasterDuke17** [comment] 2016-07-04 22:44
I would not have --parallel enabled for whatever auto-builds the docs for docs.perl6.org. I _believe_ my code is correct, but Rakudo just doesn't implement it well enough (yet). On my machine it's actually still faster to just run with --parallel a couple times until it completes, versus running it serially, but unless the script loops until the exit status is ok I'd leave it on the old behavior for the website.

**Comment by coke** [comment] 2016-12-22 02:56
The parallel code causes SEGVs and other oddities. A barebones version of htmlify that exhibits the issue is on the coke/bughunt branch

**Comment by coke** [comment] 2017-02-12 15:43
jnthn++ fixed the issues I had golfed down on the coke/bughunt branch - need to investigate what issues are left with --parallel now.

**Comment by jnthn** [comment] 2017-02-12 15:57
The remaining one I know about is the code-gen for `NEXT` phasers in `while`/`until`/`loop` has issues, which show up under recursion of concurrency. There may be further problems in htmlify.p6 and its related modules beyond those I already fixed, however. Guess we'll see after the `NEXT` bug is addressed.

**Comment by AlexDaniel** [comment] 2018-03-03 21:41
@jnthn ticket id?

**Comment by JJ** [comment] 2018-03-24 21:43
What's the current status of this? If I got this correctly, parallelization is turned off but we would like to turn it on for, among other things, speed up test, right?

**Comment by JJ** [comment] 2018-04-08 07:09
It looks like this issue has been addressed and is no longer needed. I'll close it, please clarify and reopen it if necessary.

**Closed by JJ** 2018-04-08 07:09 UTC
Labels: TPF Grant, build
