### ISSUE TITLE
Nativecall function callback syntax

### ISSUE THREAD

**Issue by CurtTilmes** [perl6/doc#2684] opened 2019-03-19 16:36 UTC
https://docs.perl6.org/language/nativecall#Function_arguments

has an example like this:

    my sub SetCallback(&callback:(Str --> int32)) is native('mylib') { * }

I'm not sure, but that syntax seems wrong to me.  I _think_ it should be: 

    my sub SetCallback(&callback (Str --> int32)) is native('mylib') { * }

(No ':', space instead).

Can someone who actually knows verify that?  (The space seems to work when I use it, while I get errors with the ':', but I don't actually know why)

**Comment by JJ** [comment] 2019-03-19 16:51
Well, it might be that the first has too many parentheses... But you are right, that syntax is wrong. However, we will have to look and check what's actually right...

**Comment by taboege** [comment] 2019-05-05 12:21
Everywhere else the colon is used to [constrain the signature of a callable](http://docs.perl6.org/type/Signature#Constraining_signatures_of_Callables), isn't it? The no-colon-but-space syntax reminds me of [destructuring](http://docs.perl6.org/type/Signature#Destructuring_arguments) which is not at all what is intended.

But I can reproduce what Curt said: with the colon I get an exception, and without the colon it works as expected, e.g. https://gist.github.com/taboege/2e95ce969d26d00342669723c1a11dd1.

I am so surprised that I bugged rakudo/rakudo#2878 about it.

**Comment by JJ** [comment] 2019-05-14 05:37
Closed via 1abe655

**Comment by treyharris** [comment] 2019-05-14 20:56
This is insufficient, @JJ — it makes the example work, but it has no explanation anywhere. Like @taboege noted, the “fixed” example _should_ be, by [Signature’s doc](http://docs.perl6.org/type/Signature#Destructuring_arguments), a destructuring, and a nonsensical one.

I don’t think there’s harm in leaving the “fixed” example, but I think this needs to stay open at least until we have some clarity from the rakudo bug on _how_ this syntax is doing what it’s doing.

I’ll annotate rakudo/rakudo#2878 about this.

**Comment by treyharris** [comment] 2019-05-14 22:10
@JJ I’m suggesting something along the lines of the pullreq #2791 — please take a look.

**Comment by JJ** [comment] 2019-07-21 08:07
Closed after merging #2791

**Closed by JJ** 2019-07-21 08:07 UTC
Labels: bug, docs
