### ISSUE TITLE
Create language/history page

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#740] opened 2016-07-22 03:32 UTC
Inspired by this recent conversation: http://irclog.perlgeek.de/perl6/2016-07-22#i_12884638

Also can be considered part of https://github.com/perl6/doc/issues/728

**Comment by JJ** [comment] 2018-04-28 10:03
This is a duplicate of #1000, which is already closed. So closing it too.

**Closed by JJ** 2018-04-28 10:03 UTC
Labels: JJ TPF Grant, docs

**Comment by AlexDaniel** [comment] 2018-04-28 11:38
Oh wow… the amount of duplicates I created is amazing. More so given that I'm usually the author of both tickets :joy:
