### ISSUE TITLE
URGENT: work to order entries on https://docs.perl6.org/language.html has broken long standing links.

### ISSUE THREAD

**Issue by coke** [perl6/doc#2202] opened 2018-07-21 05:17 UTC
https://docs.perl6.org/language.html

Now has links to pages like:

https://docs.perl6.org/language/019-unicode_entry

The original entry for this was

https://docs.perl6.org/language/unicode_entry

and now this is a 404.

If we can't fix these easily and keep the ordering, then please remove the ordering asap and put it back the way it was until we can do both.

**Comment by stmuk** [comment] 2018-07-21 06:54
See https://docs.perl6.org/build-log/build-2018-07-20T19:40+00:00.log

Note also "make html-nohighlight" is broken in a different way (it looks like changes made to the 'html' target haven't been made there).

````
$ make html-nohighlight 
perl6 htmlify.p6 --no-highlight
Initializing ...
Creating html/subdirectories ...
Reading type graph ...
Not writing type graph images, it seems to be up-to-date
To force writing of type graph images, supply the --typegraph
option at the command line, or delete
file 'html/images/type-graph-Any.svg'
Reading build/Programs ...
Failed to get the directory contents of '/home/steve/sandbox/perl6/doc/build/Programs': Failed to open dir: 2
  in code  at htmlify.p6 line 148
  in sub process-pod-dir at htmlify.p6 line 256
  in sub MAIN at htmlify.p6 line 198
  in block <unit> at htmlify.p6 line 1037

Actually thrown at:
  in block  at htmlify.p6 line 149
  in block <unit> at htmlify.p6 line 146

Makefile:30: recipe for target 'html-nohighlight' failed
make: *** [html-nohighlight] Error 1

````

**Comment by stmuk** [comment] 2018-07-21 07:12
@tbrowder I can't reproduce the error from the website log and wonder if it's due to files left from a previous run under 'build' not being cleaned up?

**Comment by JJ** [comment] 2018-07-21 09:06
I'm not sure about this error you're pointing out, but maybe it's a different issue, right?

**Comment by stmuk** [comment] 2018-07-21 09:10
@JJ No it's the same as the one you just opened as #2203

**Comment by JJ** [comment] 2018-07-21 09:32
OK, I'll then close everything when I solve #2203

**Comment by JJ** [comment] 2018-07-21 10:43
Result of a dry-run of git clean -fd
```
doc.perl6.org@hack:~/doc$ git clean -n -fd
Would remove force-update
Would remove html/build-log/
Would remove html/js/
Would remove update.log
```

**Comment by JJ** [comment] 2018-07-24 06:03
I'll work on this today.

**Comment by tbrowder** [comment] 2018-07-24 15:57
I think this is fixed now.

**Comment by JJ** [comment] 2018-07-24 15:58
Then close it, with honors :-)

**Comment by tbrowder** [comment] 2018-07-24 16:10
Closed until we get more complaints.

**Closed by tbrowder** 2018-07-24 16:10 UTC
Labels: bug, build, ⚠ Urgent ⚠
