### ISSUE TITLE
Language page has weird ascii bars

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2188] opened 2018-07-19 18:33 UTC
> \<[Coke]\> I thought the bars on titles was inserted and quickly removed; still there?
> \<Zoffix\> [Coke]: they're still on this page: https://docs.perl6.org/language.html
>  \<[Coke]\> can you open a doc ticket for that? if tb can't fix it, I'll take a shot this weekend.

![z](https://user-images.githubusercontent.com/5747918/42962825-7c8e9d40-8b60-11e8-8239-494eb0b4b126.png)

**Comment by AlexDaniel** [comment] 2018-07-19 20:44
Ah, argh… Unicode bars were removed, but Pod::To::BigPage [cries](https://docs.perl6.org/build-log/build-2018-07-19T18:05+00:00.log) if there's no subtitle… The way the table looks right now is temporary, and I believe @tbrowder++ is already working on improving that.

… so [I added](https://github.com/perl6/doc/commit/11d081bd194d58c23c0d195ed6a7c990a3d2bd5b) a `~` back into the subtitle to let the website build properly…

**Comment by tbrowder** [comment] 2018-07-19 21:01
I am working on it, so please bear it a bit longer.

**Comment by JJ** [comment] 2018-07-20 00:53
That could also be fixed. Please raise an issue...

**Comment by AlexDaniel** [comment] 2018-07-20 01:04
Actually, maybe it's not related to the subtitle because the error is still there. I simply assumed it was related to that because it felt like it failed after I removed the subtitle. I guess the issue is different.

**Comment by JJ** [comment] 2018-07-20 16:17
El vie., 20 jul. 2018 a las 3:04, Aleks-Daniel Jakimenko-Aleksejev (<
notifications@github.com>) escribió:

> Actually, maybe it's not related to the subtitle because the error is
> still there. I simply assumed it was related to that because it felt like
> it failed after I removed the subtitle. I guess the issue is different.
>

Can you please what's the issue and raise it there?

**Comment by AlexDaniel** [comment] 2018-07-20 17:23
@JJ it's actually happening again: https://docs.perl6.org/build-log/build-2018-07-20T17:05+00:00.log

I can't investigate what's going on there right now. Maybe you can do it?

**Comment by JJ** [comment] 2018-07-20 18:02
Not right now, about to board the plane. Tomorrow after a good night's
sleep

**Comment by JJ** [comment] 2018-07-24 08:20
Bars have disappeared, so closing this.

**Closed** 2018-07-24 08:31 UTC
