### ISSUE TITLE
Content in “Dynamic variables” table is slightly broken

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#759] opened 2016-07-25 18:49 UTC
https://docs.perl6.org/language/variables#Dynamic_variables

See #754 where all this started. Now the table is parsed correctly, but there is another different issue:

```
$*TMPDIR    An L<IO::Path> object representing the "system temporary directory"
$*THREAD    A L<Thread> object representing the currently executing thread.
```

Note that `L<IO::Path>` is printed as-is without turning into a link.

**Comment by awwaiid** [comment] 2016-07-27 12:39
I think this is an issue in ALL pod6 table rendering. Happens for C<...> also.

**Comment by tbrowder** [comment] 2016-07-27 13:04
On Wed, Jul 27, 2016 at 7:39 AM, Brock Wilcox <notifications@github.com> wrote:
>
> I think this is an issue in ALL pod6 table rendering. Happens for C<...> also.

As I've said previously, I think the problem is in the rendering
(Pod::To::HTML or htmlify.p6).

**Comment by JJ** [comment] 2018-05-04 17:43
Dynamic variables are no longer in a table, and the general issue has been opened elsewhere, so I'm closing this one.

**Closed by JJ** 2018-05-04 17:43 UTC
Labels: JJ TPF Grant, build
