### ISSUE TITLE
Document the trap that the last Failure in a list doesn't get sunk

### ISSUE THREAD

**Issue by kjkuan** [perl6/doc#1607] opened 2017-10-16 03:11 UTC
Example provided by Juerd:
```
perl6 -e 'sub mv ($a, $b) { for 1 { rename $a, $b } }; mv "does-not-exist", "meh";'
```
Even though `rename` returns a `Failure`, it doesn't get sunked in this context, and therefore above code fails silently.

Another example provided by geekosaur:

```
perl6 -e 'sink [1,2,Failure.new("boo!")]'
```

**Comment by AlexDaniel** [comment] 2017-10-16 03:22
Relevant issue from the ecosystem: https://github.com/perlpilot/p6-sake/issues/12

**Comment by kjkuan** [comment] 2017-10-16 18:12
I have to say that in the context of the first example(in a `for` loop), it feels more like a bug to me than a trap.

**Comment by AlexDaniel** [comment] 2017-10-16 18:42
@kjkuan you're probably right. Also, in the long run we want to get rid of (or maybe cover somehow) all traps mentioned in the docs, so a [DETRAP] ticket is appropriate in any case.

**Comment by zoffixznet** [comment] 2017-10-21 01:17
> perl6 -e 'sub mv ($a, $b) { for 1 { rename $a, $b } }; mv "does-not-exist", "meh";'

That's [a bug](https://rt.perl.org/Ticket/Display.html?id=131622)

**Comment by AlexDaniel** [comment] 2018-03-20 14:30
@zoffixznet the bug is `resolved`, but the snippet still fails silently? So was it resolved?

**Comment by AlexDaniel** [comment] 2018-03-20 14:31
@JJ FWIW, this is one more reason why we want to keep `external` tickets open ↑ (upstream ticket was marked as `resolved`, but the issue is still there)

**Comment by AlexDaniel** [comment] 2018-03-20 14:33
Oh! I just followed some links and ended up on https://github.com/rakudo/rakudo/issues/1571. I guess that's the new upstream ticket.

**Comment by zoffixznet** [comment] 2018-03-20 14:59
> @zoffixznet the bug is resolved, but the snippet still fails silently? So was it resolved?

The OP in linked ticket was resolved (failure to sink for loop), but there's another bug (failure to sink sub return) that's now in https://github.com/rakudo/rakudo/issues/1571

**Comment by JJ** [comment] 2018-05-17 06:57
List.sink is a no-op. It's explained in rakudo/rakudo#1393
It's not documented as such, though. Maybe the solution would be to document it, not put in the the Traps section.

**Closed** 2018-05-17 07:09 UTC
Labels: docs, external
