### ISSUE TITLE
... is searchable but gives 404

### ISSUE THREAD

**Issue by teodozjan** [perl6/doc#618] opened 2016-06-21 13:35 UTC
Tested in firefox and opera

**Comment by AlexDaniel** [comment] 2016-06-21 13:40
Thanks for reporting!

But it's a duplicate of https://github.com/perl6/doc/issues/155

Last news about this issue is that @jsoref had some progress. Not sure what the current status is though.

**Closed by AlexDaniel** 2016-06-21 13:40 UTC
