### ISSUE TITLE
HyperSeq and RaceSeq types are not documented

### ISSUE THREAD

**Issue by antoniogamiz** [perl6/doc#2916] opened 2019-07-25 17:21 UTC
## The problem

In my investigations about the URL state in the documentation, I have found these [two links](https://github.com/perl6/doc/blob/0436eaba216fb09e9dfbfb2fea6a8451cab46009/doc/Type/Any.pod6#L431) and I did not why they returned a 404 error. After a moment, I realized the problem was they were not documented.

## Suggestions

Document them.

**Comment by JJ** [comment] 2019-07-26 06:14
I'm afraid this is a dupe of #1897. Please add any comment there if you think there's a difference.

**Closed by JJ** 2019-07-26 06:14 UTC
Labels: docs
