### ISSUE TITLE
https://docs.perl6.org/routine/path-sep - is a method

### ISSUE THREAD

**Issue by arnesom** [perl6/doc#2559] opened 2019-01-13 02:29 UTC
## The problem

"path-sep" is a method, but the URL (https://docs.perl6.org/routine/path-sep)
implies that it is a routine.

## Suggestions

Fix the URL?

**Comment by JJ** [comment] 2019-01-13 08:36
Thanks for the report.

**Comment by JJ** [comment] 2019-01-13 13:46
Really grateful for this. No need to add more. There are plenty of them; I have created the issue referenced above (#2560 in case you're reading this via email) and re-vivified #1433.

**Comment by cfa** [comment] 2019-01-13 16:34
Is this a bug? I thought methods have historically been listed under `/routine`.

CC @moritz @coke

**Comment by JJ** [comment] 2019-01-13 16:52
Yep, it is. As indicated in #2560, their expansion was wrong originally and different of the actual HTML documents that were generated.
It's a bug in any case. Either
1. It's generated under `method` and should be generated under `routine`, or
2. The link to `routine/x` is wrong.

Again, this is related to the (sometimes) twisted logic htmlify.p6 #1823 follows, which we need to spec in order to fix it or get rid of it.

**Comment by cfa** [comment] 2019-01-13 16:54
But these aren't all expansions from implicit links, right? If the intention was to group methods and routines together under `/routine`, this isn't a bug but by design.

**Comment by JJ** [comment] 2019-01-13 17:03
The ones that are failing are. And, as indicated above, I have no idea what the "design" was. That's why we need a test suite for the current setup.

**Comment by moritz** [comment] 2019-05-03 20:38
Closing now, since a routine is a method, and so available under the URL `routine` is not a bug.

**Closed by moritz** 2019-05-03 20:38 UTC
Labels: bug, docs
